use Mix.Config
config :video_processor,
  complex_feed_url: "http://test-url",
  uplynk_account_guid: "test",
  uplynk_secret_key: "test",
  s3_url: "test"
config :ex_aws,
  access_key_id: "test",
  secret_access_key: "test",
  upload_bucket: "test"
